INSERT INTO location VALUES ('LName','Description');
INSERT INTO location VALUES ('Pallet Town','A fairly new and quiet town. Its a small and pretty place.');
INSERT INTO location VALUES ('Viridian City','A beautiful city that is enveloped in green year-round.');
INSERT INTO location VALUES ('Pewter City','A quiet city nestled between rugged mountains and rocks.');
INSERT INTO location VALUES ('Cerulean City','A beautiful city with flowing water and blooming flowers.');
INSERT INTO location VALUES ('Vermilion City','A southern city that is bathed in orange by the setting sun.');
INSERT INTO location VALUES ('Lavender Town','A small town covered in a beautiful hue of purple.');
INSERT INTO location VALUES ('Celadon City','A rich rainbow colored city where people and Pokémon gather.');
INSERT INTO location VALUES ('Fuchsia City','A historic village that has become new.');
INSERT INTO location VALUES ('Saffron City','The biggest city in Kanto shining with a golden light.');
INSERT INTO location VALUES ('Cinnabar Island','A town used to be here until it was swept away by an eruption.');
INSERT INTO location VALUES ('Cerulean Cave','A mysterious cave that is filled with terribly tough Pokémon. It is so dangerous the Pokémon League is in charge of it');
INSERT INTO location VALUES ('Digletts Cave','A seemingly plain tunnel that was dug by wild Diglett. It is famous for connecting Routes 2 and 11');
INSERT INTO location VALUES ('Fighting Dojo','Former Pokemon Gym located in Saffron City');
INSERT INTO location VALUES ('Indigo Plateau','The fate of many Trainers aiming for the top rests here.');
INSERT INTO location VALUES ('Mt. Moon','A mystical mountain that is known for its frequent meteor falls. The shards of stars that fall here are known as Moon Stones.');
INSERT INTO location VALUES ('Pokemon Mansion','A decrepit burned-down mansion on Cinnabar Island. It got its name because a famous Pokémon researcher lived there.');
INSERT INTO location VALUES ('Pokemon Tower','A tower that houses the graves of countless Pokémon. Many people visit it daily to pay their respects to the fallen');
INSERT INTO location VALUES ('Power Plant','A power plant that was abandoned years ago though some of the machines still work. It is infested with electric Pokémon');
INSERT INTO location VALUES ('Rock Tunnel','A naturally formed underground tunnel. Because it has not been developed it is inky dark inside. A light is needed to get through.');
INSERT INTO location VALUES ('Celadon Game Corner','A fun time Casino');
INSERT INTO location VALUES ('Safari Zone','An amusement park outside Fuchsia City where many rare Pokémon can be observed in the wild. Catch them in a popular game!');
INSERT INTO location VALUES ('Seafoam Islands','A pair of islands that is situated on Route 20. The two islands are shaped the same as if they were twins.');
INSERT INTO location VALUES ('Silph Co.','They are the manufacturers of many tools including the Silph Scope—a device that allows the user to view spectral entities—as well as home appliances.');
INSERT INTO location VALUES ('Victory Road','A tunnel situated on Route 23. It earned its name because it must be traveled by all Trainers aiming for the top.');
INSERT INTO location VALUES ('Virdian Forest','A deep and sprawling forest that extends around Viridian City. A natural maze many people become lost inside.');
INSERT INTO location VALUES ('Route 1','A country road full of greenery and rough paths.');
INSERT INTO location VALUES ('Route 2','A path that winds and bends from the forest entrance.');
INSERT INTO location VALUES ('Route 3','A road where many rocks have fallen from the sky to create craters.');
INSERT INTO location VALUES ('Route 4','A one-way road down a hill that has a gentle slope and is fun to traverse.');
INSERT INTO location VALUES ('Route 5','A road running north of Saffron City connecting to the Underground Path.');
INSERT INTO location VALUES ('Route 6','A road running south of Saffron City connecting to the Underground Path.');
INSERT INTO location VALUES ('Route 7','A short road that leads to the blocked-off Underground Path.');
INSERT INTO location VALUES ('Route 8','Route 8 is a unique route traveling along east to west from Lavender Town to Saffron City.');
INSERT INTO location VALUES ('Route 9','A road that forms a maze crossing a small rocky mountain.');
INSERT INTO location VALUES ('Route 10','A road that passes along the canal and comes out at the Power Plant.');
INSERT INTO location VALUES ('Route 11','A grassy path with a gentle refreshing breeze.');
INSERT INTO location VALUES ('Route 12','A bridge known for its fishing. It also called Silence Bridge.');
INSERT INTO location VALUES ('Route 13','A difficult narrow path where many Trainers await you');
INSERT INTO location VALUES ('Route 14','A pleasant coastal road where the breeze blows and waves roar.');
INSERT INTO location VALUES ('Route 15','A path that cuts through the row of trees to come out on the coastline.');
INSERT INTO location VALUES ('Route 16','The northern starting point of Cycling Road.');
INSERT INTO location VALUES ('Route 17','An easy path of Cycling Road running above the sea.');
INSERT INTO location VALUES ('Route 18','The southern ending point of Cycling Road.');
INSERT INTO location VALUES ('Route 19','A coastal road littered with rocks due to Cinnabar Island volcano eruption.');
INSERT INTO location VALUES ('Route 20','A popular path with swimmers. The Seafoam Islands are also here.');
INSERT INTO location VALUES ('Route 21','A coastal road where the only threat might be the volcano on the horizon.');
INSERT INTO location VALUES ('Route 22','A path to Victory Road that eventually becomes impassable.');
INSERT INTO location VALUES ('Route 23','A route in northwest Kanto connecting Indigo Plateau to Victory Road and Route 22.');
INSERT INTO location VALUES ('Route 24','A beautiful bridge that stretches across a river.');
INSERT INTO location VALUES ('Route 25','A path that winds through the forest and comes out overlooking the sea.');
