INSERT INTO poke_found VALUES ('1','Professor Oak Lab');
INSERT INTO poke_found VALUES ('2','Evolved from Bulbasaur');
INSERT INTO poke_found VALUES ('3','Evolve from Ivysaur');
INSERT INTO poke_found VALUES ('4','Professor Oak Lab');
INSERT INTO poke_found VALUES ('5','Evolved from Charmander');
INSERT INTO poke_found VALUES ('6','Evolved from Charmeleon');
INSERT INTO poke_found VALUES ('7','Professor Oak Lab');
INSERT INTO poke_found VALUES ('8','Evolved from Squirtle');
INSERT INTO poke_found VALUES ('9','Evolved from Wartortle');
INSERT INTO poke_found VALUES ('10','Viridian Forest Route 2 Route 24 & 25');
INSERT INTO poke_found VALUES ('11','Viridian Forest Route 24 & 25');
INSERT INTO poke_found VALUES ('12','Evolved from Metapod');
INSERT INTO poke_found VALUES ('13','Viridian ForestRoute 2 Route 24 & 25');
INSERT INTO poke_found VALUES ('14','Viridian Forest Route 24 & 25');
INSERT INTO poke_found VALUES ('15','Evolved from Kakuna');
INSERT INTO poke_found VALUES ('16','Lots of places! About 14');
INSERT INTO poke_found VALUES ('17','Route 21 14 & 15');
INSERT INTO poke_found VALUES ('18','Evolved from Pidgeotto');
INSERT INTO poke_found VALUES ('19','Lots of places about 11');
INSERT INTO poke_found VALUES ('20','Route 16 17 18 and 21');
INSERT INTO poke_found VALUES ('21','Lots of places about 9');
INSERT INTO poke_found VALUES ('22','Route 17 18 and 23');
INSERT INTO poke_found VALUES ('23','Lots of places about 5');
INSERT INTO poke_found VALUES ('24','Route 23 and Unknown Dungeon');
INSERT INTO poke_found VALUES ('25','Viridian Forest and the Power Plant');
INSERT INTO poke_found VALUES ('26','Route 23 the Power Plant and Unknown Dungeon');
INSERT INTO poke_found VALUES ('27','Lots of places about 5');
INSERT INTO poke_found VALUES ('28','Route 23 and Unknown Dungeon');
INSERT INTO poke_found VALUES ('29','Route 22 and Safari Zone');
INSERT INTO poke_found VALUES ('30','Safari Zone Celedon City and Route 11');
INSERT INTO poke_found VALUES ('31','Evolved from Nidorina');
INSERT INTO poke_found VALUES ('32','Route 22 and Safari Zone');
INSERT INTO poke_found VALUES ('33','Safari Zone and Celedon City');
INSERT INTO poke_found VALUES ('34','evolved from Nidorino');
INSERT INTO poke_found VALUES ('35','Mt. Moon Celedon City and Unknown Dungeon');
INSERT INTO poke_found VALUES ('36','Evolved from Clefairy');
INSERT INTO poke_found VALUES ('37','Pokemon Mansion Route 7 and 8');
INSERT INTO poke_found VALUES ('38','Evolved from Vulpix');
INSERT INTO poke_found VALUES ('39','Route 3');
INSERT INTO poke_found VALUES ('40','the Unknown Dungeon');
INSERT INTO poke_found VALUES ('41','Mt. Moon Rock Tunnel Victory Road and Seafoam Island');
INSERT INTO poke_found VALUES ('42','Route 23 Victory Road and Seafoam Island');
INSERT INTO poke_found VALUES ('43','Lots of places about 9');
INSERT INTO poke_found VALUES ('44','Route 15 14 13 and 12');
INSERT INTO poke_found VALUES ('45','Evolved from Gloom');
INSERT INTO poke_found VALUES ('46','Mt. Moon and Safari Zone');
INSERT INTO poke_found VALUES ('47','Safari Zone and Unknown Dungeon');
INSERT INTO poke_found VALUES ('48','Route 15 14 13 12 and Safari Zone');
INSERT INTO poke_found VALUES ('49','Victory Road Safari Zone and Unknown Dungeon');
INSERT INTO poke_found VALUES ('50','Diglett Cave');
INSERT INTO poke_found VALUES ('51','Diglett Cave');
INSERT INTO poke_found VALUES ('52','Route 8 7 6 and 5');
INSERT INTO poke_found VALUES ('53','Evolved from Meowth');
INSERT INTO poke_found VALUES ('54','Lots of places about 6');
INSERT INTO poke_found VALUES ('55','Seafoam Island');
INSERT INTO poke_found VALUES ('56','Route 8 7 6 and 5');
INSERT INTO poke_found VALUES ('57','Evolved from Mankey');
INSERT INTO poke_found VALUES ('58','Route 7 8 and the Pokemon Mansion');
INSERT INTO poke_found VALUES ('59','Evolved from Growlithe');
INSERT INTO poke_found VALUES ('60','Fish for him');
INSERT INTO poke_found VALUES ('61','Fish for him');
INSERT INTO poke_found VALUES ('62','Evolved from Poliwhirl');
INSERT INTO poke_found VALUES ('63','Celedon Ex. corner Route 24 and 25');
INSERT INTO poke_found VALUES ('64','The Unknown Dungeon');
INSERT INTO poke_found VALUES ('65','Evolved from Kadabra');
INSERT INTO poke_found VALUES ('66','Victory Road and Rock Tunnel');
INSERT INTO poke_found VALUES ('67','Victory Road');
INSERT INTO poke_found VALUES ('68','Evolved from Machoke');
INSERT INTO poke_found VALUES ('69','Lots of places about 9');
INSERT INTO poke_found VALUES ('70','Route 12 13 14 and 15');
INSERT INTO poke_found VALUES ('71','Evolved from Weepinbell');
INSERT INTO poke_found VALUES ('72','fish for him');
INSERT INTO poke_found VALUES ('73','Evolved from Tentacool');
INSERT INTO poke_found VALUES ('74','Mt. Moon Rock Tunnel and Victory Road');
INSERT INTO poke_found VALUES ('75','Victory Road');
INSERT INTO poke_found VALUES ('76','Evolved from Graveler');
INSERT INTO poke_found VALUES ('77','Pokemon Mansion');
INSERT INTO poke_found VALUES ('78','Evolved from Ponyta');
INSERT INTO poke_found VALUES ('79','fish for him');
INSERT INTO poke_found VALUES ('80','fish for him');
INSERT INTO poke_found VALUES ('81','the Unknown Dungeon and the Power Plant');
INSERT INTO poke_found VALUES ('82','the Unknown Dungeon and the Power Plant');
INSERT INTO poke_found VALUES ('83','Vermilion City (trade Spearow)');
INSERT INTO poke_found VALUES ('84','Route 16 17 18 and Safari Zone');
INSERT INTO poke_found VALUES ('85','the Unknown Dungeon');
INSERT INTO poke_found VALUES ('86','Seafoam Island');
INSERT INTO poke_found VALUES ('87','Seafoam Island');
INSERT INTO poke_found VALUES ('88','Pokemon Mansion');
INSERT INTO poke_found VALUES ('89','the Unknown Dungeon');
INSERT INTO poke_found VALUES ('90','fish for him');
INSERT INTO poke_found VALUES ('91','Evolved from Shellder');
INSERT INTO poke_found VALUES ('92','Pokemon Tower');
INSERT INTO poke_found VALUES ('93','Pokemon Tower');
INSERT INTO poke_found VALUES ('94','Evolved from Haunter');
INSERT INTO poke_found VALUES ('95','Victory Road and Rock Tunnel');
INSERT INTO poke_found VALUES ('96','Route 11');
INSERT INTO poke_found VALUES ('97','the Unknown Dungeon');
INSERT INTO poke_found VALUES ('98','fish for him');
INSERT INTO poke_found VALUES ('99','Route 23 (fish) Seafoam Island and the Unknown Dungeon');
INSERT INTO poke_found VALUES ('100','Power Plant and Route 9');
INSERT INTO poke_found VALUES ('101','Unknown Dungeon Power Plant Cinibar Island and');
INSERT INTO poke_found VALUES ('102','Safari Zone');
INSERT INTO poke_found VALUES ('103','Evolved from Exeggcute');
INSERT INTO poke_found VALUES ('104','Pokemon Tower');
INSERT INTO poke_found VALUES ('105','Victroy Road and Unknown Dungeon');
INSERT INTO poke_found VALUES ('106','Saffron City (beat the fighting do-jo)');
INSERT INTO poke_found VALUES ('107','Saffron City (beat the fighting do-jo)');
INSERT INTO poke_found VALUES ('108','Route 18 (trade Slowbro in the building)');
INSERT INTO poke_found VALUES ('109','Pokemon Mansion');
INSERT INTO poke_found VALUES ('110','Pokemon Mansion');
INSERT INTO poke_found VALUES ('111','Safari Zone');
INSERT INTO poke_found VALUES ('112','Unknown Dungeon');
INSERT INTO poke_found VALUES ('113','Safari Zone and Unknown Dungeon');
INSERT INTO poke_found VALUES ('114','Route 21 and Cinnabar Island');
INSERT INTO poke_found VALUES ('115','Safari Zone');
INSERT INTO poke_found VALUES ('116','Fish for him');
INSERT INTO poke_found VALUES ('117','Fish for him');
INSERT INTO poke_found VALUES ('118','Fish for her');
INSERT INTO poke_found VALUES ('119','Fish for her');
INSERT INTO poke_found VALUES ('120','Fish for her/him');
INSERT INTO poke_found VALUES ('121','Evolved from Staryu');
INSERT INTO poke_found VALUES ('122','Viridian City on the right side where you use the CUT ability trade Abra');
INSERT INTO poke_found VALUES ('123','Celedon ex. Corner (Red) and Safari Zone');
INSERT INTO poke_found VALUES ('124','Cerulean City (trade Poliwhirl)');
INSERT INTO poke_found VALUES ('125','Power Plant');
INSERT INTO poke_found VALUES ('126','Pokemon Mansion');
INSERT INTO poke_found VALUES ('127','Celedon ex. Corner (Blue) and Safari Zone');
INSERT INTO poke_found VALUES ('128','Safari Zone');
INSERT INTO poke_found VALUES ('129','Fish for him');
INSERT INTO poke_found VALUES ('130','Evolved from Magikarp');
INSERT INTO poke_found VALUES ('131','Silph Co. (floor 7)');
INSERT INTO poke_found VALUES ('132','Lots of places about 5');
INSERT INTO poke_found VALUES ('133','Celedon City (go around back of Celedon Mansion)');
INSERT INTO poke_found VALUES ('134','Evolved from Eevee');
INSERT INTO poke_found VALUES ('135','Evolved from Eevee');
INSERT INTO poke_found VALUES ('136','Evolved from Eevee');
INSERT INTO poke_found VALUES ('137','Celedon ex. Corner');
INSERT INTO poke_found VALUES ('138','Take the Helix fossil to Cinnabar Island and go to the Pokemon Lab');
INSERT INTO poke_found VALUES ('139','Evolved from Omanyte');
INSERT INTO poke_found VALUES ('140','Take the Dome fossil to Cinnabar Island and go to the Pokemon Lab');
INSERT INTO poke_found VALUES ('141','Evolved from Kabuto');
INSERT INTO poke_found VALUES ('142','Take the Old Amber to Cinnabar Island and go to the Pokemon Lab');
INSERT INTO poke_found VALUES ('143','Route 12 and 16 (the sleeping Pokemon in the middle of the Routes)');
INSERT INTO poke_found VALUES ('144','Seafoam Island (one chance to get Pokemon)');
INSERT INTO poke_found VALUES ('145','Power Plant(one chance to get Pokemon)');
INSERT INTO poke_found VALUES ('146','Victory Road (one chance to get Pokemon)');
INSERT INTO poke_found VALUES ('147','Celedon ex. Corner and Safari Zone');
INSERT INTO poke_found VALUES ('148','Evolved from Dratini');
INSERT INTO poke_found VALUES ('149','Evolved from Dragonair');
INSERT INTO poke_found VALUES ('150','The Unknown Dungeon');
INSERT INTO poke_found VALUES ('151','Look in the Cheats section for Red/Blue.');
