INSERT INTO trainer VALUES ('Rival_1','13, 10');
INSERT INTO trainer VALUES ('Bug Catcher Rick','13, 14, 13');
INSERT INTO trainer VALUES ('Bug Catcher Doug','10');
INSERT INTO trainer VALUES ('Bug Catcher Anthony','50, 27');
INSERT INTO trainer VALUES ('Bug Catcher Charlie','74, 95');
INSERT INTO trainer VALUES ('Bug Catcher Sammy','13, 11');
INSERT INTO trainer VALUES ('Camper Liam','13, 14, 14');
INSERT INTO trainer VALUES ('Leader Brock','11');
INSERT INTO trainer VALUES ('Lass Janice','50, 28');
INSERT INTO trainer VALUES ('Bug Catcher Colton','74, 96');
INSERT INTO trainer VALUES ('Youngster Ben','13, 12');
INSERT INTO trainer VALUES ('Bug Catcher Greg','13, 14, 15');
INSERT INTO trainer VALUES ('Lass Sally','13, 11');
INSERT INTO trainer VALUES ('Bug Catcher James','13, 14, 14');
INSERT INTO trainer VALUES ('Youngster Calvin','11');
INSERT INTO trainer VALUES ('Lass Robin','50, 28');
INSERT INTO trainer VALUES ('Lass Iris','74, 96');
INSERT INTO trainer VALUES ('Bug Catcher Kent','13, 12');
INSERT INTO trainer VALUES ('Super Nerd Jovan','13, 14, 15');
INSERT INTO trainer VALUES ('Bug Catcher Robby','12');
INSERT INTO trainer VALUES ('Lass Miriam','50, 29');
INSERT INTO trainer VALUES ('Team Rocket Grunt_1','74, 97');
INSERT INTO trainer VALUES ('Team Rocket Grunt_2','13, 13');
INSERT INTO trainer VALUES ('Youngster Josh','13, 14, 16');
INSERT INTO trainer VALUES ('Hiker Marcos','13, 12');
INSERT INTO trainer VALUES ('Team Rocket Grunt_3','13, 14, 15');
INSERT INTO trainer VALUES ('Team Rocket Grunt_4','12');
INSERT INTO trainer VALUES ('Super Nerd Miguel','50, 29');
INSERT INTO trainer VALUES ('Lass Crissy','74, 97');
INSERT INTO trainer VALUES ('Rival_2','13, 13');
INSERT INTO trainer VALUES ('Bug Catcher Cale','13, 14, 16');
INSERT INTO trainer VALUES ('Lass Ali','13');
INSERT INTO trainer VALUES ('Youngster Timmy','50, 30');
INSERT INTO trainer VALUES ('Lass Reli','74, 98');
INSERT INTO trainer VALUES ('Camper Ethan','13, 14');
INSERT INTO trainer VALUES ('Team Rocket Grunt_5','13, 14, 17');
INSERT INTO trainer VALUES ('Camper Shane','13, 13');
INSERT INTO trainer VALUES ('Hiker Franklin','13, 14, 16');
INSERT INTO trainer VALUES ('Hiker Wayne','13');
INSERT INTO trainer VALUES ('Youngster Joey','50, 30');
INSERT INTO trainer VALUES ('Youngester Dan','74, 98');
INSERT INTO trainer VALUES ('Picnicker Kelsey','13, 14');
INSERT INTO trainer VALUES ('Hiker Nob','13, 14, 17');
INSERT INTO trainer VALUES ('Camper Flint','14');
INSERT INTO trainer VALUES ('Youngster Chad','50, 31');
INSERT INTO trainer VALUES ('Lass Haley','74, 99');
INSERT INTO trainer VALUES ('Swimmer Luis','13, 15');
INSERT INTO trainer VALUES ('Picnicker Diana','13, 14, 18');
INSERT INTO trainer VALUES ('Leader Misty','13, 14');
INSERT INTO trainer VALUES ('Team Rocket Grunt_6','13, 14, 17');
INSERT INTO trainer VALUES ('Bug Catcher Keigo','14');
INSERT INTO trainer VALUES ('Camper Ricky','50, 31');
INSERT INTO trainer VALUES ('Picnicker Nancy','74, 99');
INSERT INTO trainer VALUES ('Bug Catcher Elijah','13, 15');
INSERT INTO trainer VALUES ('Picnicker Isabelle','13, 14, 18');
INSERT INTO trainer VALUES ('Camper Jeff','15');
INSERT INTO trainer VALUES ('Youngster Eddie','50, 32');
INSERT INTO trainer VALUES ('Gamer Hugo','74, 100');
INSERT INTO trainer VALUES ('Engineer Bernie','13, 16');
INSERT INTO trainer VALUES ('Gamer Jasper','13, 14, 19');
INSERT INTO trainer VALUES ('Youngster Dave','13, 15');
INSERT INTO trainer VALUES ('Youngster Dillon','13, 14, 18');
INSERT INTO trainer VALUES ('Engineer Braxton','15');
INSERT INTO trainer VALUES ('Youngster Yasu','50, 32');
INSERT INTO trainer VALUES ('Gamer Darian','74, 100');
INSERT INTO trainer VALUES ('Gamer Dirk','13, 16');
INSERT INTO trainer VALUES ('Fisherman Barny','13, 14, 19');
INSERT INTO trainer VALUES ('Sailer Phillip','16');
INSERT INTO trainer VALUES ('Sailer Huey','50, 33');
INSERT INTO trainer VALUES ('Sailor Dylan','74, 101');
INSERT INTO trainer VALUES ('Sailor Duncan','13, 17');
INSERT INTO trainer VALUES ('Sailor leonard','13, 14, 20');
INSERT INTO trainer VALUES ('Gentleman Thomas','13, 16');
INSERT INTO trainer VALUES ('Gentleman Arthur','13, 14, 19');
INSERT INTO trainer VALUES ('Lass Ann','16');
INSERT INTO trainer VALUES ('Youngster Tyler','50, 33');
INSERT INTO trainer VALUES ('Sailor Trevor','74, 101');
INSERT INTO trainer VALUES ('Sailor Edmond','13, 17');
INSERT INTO trainer VALUES ('Fisherman Dale','13, 14, 20');
INSERT INTO trainer VALUES ('Gentleman Brooks','17');
INSERT INTO trainer VALUES ('Lass Dawn','50, 34');
INSERT INTO trainer VALUES ('Gentleman Lamar','74, 102');
INSERT INTO trainer VALUES ('Rival_3','13, 18');
INSERT INTO trainer VALUES ('Sailor Dwayne','13, 14, 21');
INSERT INTO trainer VALUES ('Engineer Baily','13, 17');
INSERT INTO trainer VALUES ('Gentleman Tucker','13, 14, 20');
INSERT INTO trainer VALUES ('Leader Lt. Surge','17');
INSERT INTO trainer VALUES ('Picnicker Alicia','50, 34');
INSERT INTO trainer VALUES ('Hiker Jeremy','74, 102');
INSERT INTO trainer VALUES ('Camper Chris','13, 18');
INSERT INTO trainer VALUES ('Bug Catcher Brent','13, 14, 21');
INSERT INTO trainer VALUES ('Bug Catcher Conner','18');
INSERT INTO trainer VALUES ('Bug Camper Drew','50, 35');
INSERT INTO trainer VALUES ('Hiker Alan','74, 103');
INSERT INTO trainer VALUES ('Hiker Brice','13, 19');
INSERT INTO trainer VALUES ('Picnicker Caitlin','13, 14, 22');
INSERT INTO trainer VALUES ('Picnicker Heidi','13, 18');
INSERT INTO trainer VALUES ('Picnicker Carol','13, 14, 21');
INSERT INTO trainer VALUES ('Hiker Clark','18');
INSERT INTO trainer VALUES ('Hiker Trent','50, 35');
INSERT INTO trainer VALUES ('Pokemaniac Herman','74, 103');
INSERT INTO trainer VALUES ('Pokemaniac Mark','13, 19');
INSERT INTO trainer VALUES ('Pokemaniac Ashton','13, 14, 22');
INSERT INTO trainer VALUES ('Pokemaniac Winston','19');
INSERT INTO trainer VALUES ('Picnicker Martha','50, 36');
INSERT INTO trainer VALUES ('Pokemaniac Steve','74, 104');
INSERT INTO trainer VALUES ('Hiker Allen','13, 20');
INSERT INTO trainer VALUES ('Hiker Eric','13, 14, 23');
INSERT INTO trainer VALUES ('Hiker Lenny','13, 19');
INSERT INTO trainer VALUES ('Hiker Oliver','13, 14, 22');
INSERT INTO trainer VALUES ('Hiker Lucas','19');
INSERT INTO trainer VALUES ('Picnicker Sofia','50, 36');
INSERT INTO trainer VALUES ('Hiker Dudley','74, 104');
INSERT INTO trainer VALUES ('Pokemaniac Cooper','13, 20');
INSERT INTO trainer VALUES ('Picnicker Leah','13, 14, 23');
INSERT INTO trainer VALUES ('Picnicker Arianna','20');
INSERT INTO trainer VALUES ('Picnicker Dana','50, 37');
INSERT INTO trainer VALUES ('Lass Julia','74, 105');
INSERT INTO trainer VALUES ('Gamer Rich','13, 21');
INSERT INTO trainer VALUES ('Super Nerd Glenn','13, 14, 24');
INSERT INTO trainer VALUES ('Lass Megan','13, 20');
INSERT INTO trainer VALUES ('Lass Andrea','13, 14, 23');
INSERT INTO trainer VALUES ('Super Nerd Leslie','20');
INSERT INTO trainer VALUES ('Lass Paige','50, 37');
INSERT INTO trainer VALUES ('Biker Jaren','74, 105');
INSERT INTO trainer VALUES ('Biker Ricardo','13, 21');
INSERT INTO trainer VALUES ('Super Nerd Aiden','13, 14, 24');
INSERT INTO trainer VALUES ('Gamer Stan','21');
INSERT INTO trainer VALUES ('Lass Kay','50, 38');
INSERT INTO trainer VALUES ('Beauty Bridget','74, 106');
INSERT INTO trainer VALUES ('Picnicker Tina','13, 22');
INSERT INTO trainer VALUES ('Beauty Tamia','13, 14, 25');
INSERT INTO trainer VALUES ('Beauty Lori','13, 21');
INSERT INTO trainer VALUES ('Lass Lisa','13, 14, 24');
INSERT INTO trainer VALUES ('Cooltrainer Mary','21');
INSERT INTO trainer VALUES ('Leader Erika','50, 38');
INSERT INTO trainer VALUES ('Team Rocket Grunt_7','74, 106');
INSERT INTO trainer VALUES ('Team Rocket Grunt_8','13, 22');
INSERT INTO trainer VALUES ('Team Rocket Grunt_9','13, 14, 25');
INSERT INTO trainer VALUES ('Team Rocket Grunt_10','22');
INSERT INTO trainer VALUES ('Team Rocket Grunt_11','50, 39');
INSERT INTO trainer VALUES ('Team Rocket Grunt_12','74, 107');
INSERT INTO trainer VALUES ('Team Rocket Grunt_13','13, 23');
INSERT INTO trainer VALUES ('Team Rocket Grunt_14','13, 14, 26');
INSERT INTO trainer VALUES ('Team Rocket Grunt_15','13, 22');
INSERT INTO trainer VALUES ('Team Rocket Grunt_16','13, 14, 25');
INSERT INTO trainer VALUES ('Team Rocket Grunt_17','22');
INSERT INTO trainer VALUES ('Boss Giovanni_1','50, 39');
INSERT INTO trainer VALUES ('Rival_7','74, 107');
INSERT INTO trainer VALUES ('Channeler Hope','13, 23');
INSERT INTO trainer VALUES ('Channeler Patricia','13, 14, 26');
INSERT INTO trainer VALUES ('Channeler Carly','23');
INSERT INTO trainer VALUES ('Channeler Laurel','50, 40');
INSERT INTO trainer VALUES ('Channeler Jody','74, 108');
INSERT INTO trainer VALUES ('Channeler Paula','13, 24');
INSERT INTO trainer VALUES ('Channeler Ruth','13, 14, 27');
INSERT INTO trainer VALUES ('Channeler Tammy','13, 23');
INSERT INTO trainer VALUES ('Channeler Karina','13, 14, 26');
INSERT INTO trainer VALUES ('Channeler janae','23');
INSERT INTO trainer VALUES ('Channeler Angelica','50, 40');
INSERT INTO trainer VALUES ('Channeler Jennifer','74, 108');
INSERT INTO trainer VALUES ('Channeler Emilia','13, 24');
INSERT INTO trainer VALUES ('Team Rocket Grunt_18','13, 14, 27');
INSERT INTO trainer VALUES ('Team Rocket Grunt_19','24');
INSERT INTO trainer VALUES ('Team Rocket Grunt_20','50, 41');
INSERT INTO trainer VALUES ('Biker Lao','74, 109');
INSERT INTO trainer VALUES ('Cue Ball Luke','13, 25');
INSERT INTO trainer VALUES ('Cue Ball Koji','13, 14, 28');
INSERT INTO trainer VALUES ('Biker Hideo','13, 24');
INSERT INTO trainer VALUES ('Biker Ruben','13, 14, 27');
INSERT INTO trainer VALUES ('Cue Ball Camron','24');
INSERT INTO trainer VALUES ('Cue Ball Isaiah','50, 41');
INSERT INTO trainer VALUES ('Biker Virgil','74, 109');
INSERT INTO trainer VALUES ('Cue Ball Raul','13, 25');
INSERT INTO trainer VALUES ('Biker Billy','13, 14, 28');
INSERT INTO trainer VALUES ('Biker Nikolas','25');
INSERT INTO trainer VALUES ('Cue Ball Zeek','50, 42');
INSERT INTO trainer VALUES ('Cue Ball Corey','74, 110');
INSERT INTO trainer VALUES ('Biker Jaxon','13, 26');
INSERT INTO trainer VALUES ('Cue Ball Jamal','13, 14, 29');
INSERT INTO trainer VALUES ('Biker William','13, 25');
INSERT INTO trainer VALUES ('Bird Keeper Jacob','13, 14, 28');
INSERT INTO trainer VALUES ('Bird Keeper Wilton','25');
INSERT INTO trainer VALUES ('Bird Keeper Ramiro','50, 42');
INSERT INTO trainer VALUES ('Juggler Nate','74, 110');
INSERT INTO trainer VALUES ('Juggler Kayden','13, 26');
INSERT INTO trainer VALUES ('Juggler Kirk','13, 14, 29');
INSERT INTO trainer VALUES ('Tamer Edgar','26');
INSERT INTO trainer VALUES ('Tamer Phil','50, 43');
INSERT INTO trainer VALUES ('Juggler Shawn','74, 111');
INSERT INTO trainer VALUES ('Leader Koga','13, 27');
INSERT INTO trainer VALUES ('Black Belt Hitoshi','13, 14, 30');
INSERT INTO trainer VALUES ('Black Belt Hideki','13, 26');
INSERT INTO trainer VALUES ('Black Belt Aaron','13, 14, 29');
INSERT INTO trainer VALUES ('Black Belt Mike','26');
INSERT INTO trainer VALUES ('Black Belt Koichi','50, 43');
INSERT INTO trainer VALUES ('Team Rocket Grunt_21','74, 111');
INSERT INTO trainer VALUES ('Team Rocket Grunt_22','13, 27');
INSERT INTO trainer VALUES ('Team Rocket Grunt_23','13, 14, 30');
INSERT INTO trainer VALUES ('Team Rocket Grunt_24','27');
INSERT INTO trainer VALUES ('Team Rocket Grunt_25','50, 44');
INSERT INTO trainer VALUES ('Team Rocket Grunt_26','74, 112');
INSERT INTO trainer VALUES ('Team Rocket Grunt_27','13, 28');
INSERT INTO trainer VALUES ('Team Rocket Grunt_28','13, 14, 31');
INSERT INTO trainer VALUES ('Team Rocket Grunt_29','13, 27');
INSERT INTO trainer VALUES ('Team Rocket Grunt_30','13, 14, 30');
INSERT INTO trainer VALUES ('Team Rocket Grunt_31','27');
INSERT INTO trainer VALUES ('Team Rocket Grunt_32','50, 44');
INSERT INTO trainer VALUES ('Team Rocket Grunt_33','74, 112');
INSERT INTO trainer VALUES ('Team Rocket Grunt_34','13, 28');
INSERT INTO trainer VALUES ('Team Rocket Grunt_35','13, 14, 31');
INSERT INTO trainer VALUES ('Team Rocket Grunt_36','28');
INSERT INTO trainer VALUES ('Team Rocket Grunt_37','50, 45');
INSERT INTO trainer VALUES ('Team Rocket Grunt_38','74, 113');
INSERT INTO trainer VALUES ('Team Rocket Grunt_39','13, 29');
INSERT INTO trainer VALUES ('Scientist Jerry','13, 14, 32');
INSERT INTO trainer VALUES ('Scientist Jose','13, 28');
INSERT INTO trainer VALUES ('Scientist Rodney','13, 14, 31');
INSERT INTO trainer VALUES ('Scientist Beau','28');
INSERT INTO trainer VALUES ('Juggler Dalton','50, 45');
INSERT INTO trainer VALUES ('Scientist Taylor','74, 113');
INSERT INTO trainer VALUES ('Scientist Joshua','13, 29');
INSERT INTO trainer VALUES ('Rival_6','13, 14, 32');
INSERT INTO trainer VALUES ('Scientist Parker','29');
INSERT INTO trainer VALUES ('Scientist Ed','50, 46');
INSERT INTO trainer VALUES ('Scientist Travis','74, 114');
INSERT INTO trainer VALUES ('Boss Giovanni_2','13, 30');
INSERT INTO trainer VALUES ('Psychic Cameron','13, 14, 33');
INSERT INTO trainer VALUES ('Channeler Tasha','13, 29');
INSERT INTO trainer VALUES ('Psychic Johan','13, 14, 32');
INSERT INTO trainer VALUES ('Psychic Tyron','29');
INSERT INTO trainer VALUES ('Channeler Stacy','50, 46');
INSERT INTO trainer VALUES ('Channeler Amanda','74, 114');
INSERT INTO trainer VALUES ('Psychic Preston','13, 30');
INSERT INTO trainer VALUES ('Leader Sabrina','13, 14, 33');
INSERT INTO trainer VALUES ('Fisherman Ned','30');
INSERT INTO trainer VALUES ('Fisherman Chip','50, 47');
INSERT INTO trainer VALUES ('Fisherman Hank','74, 115');
INSERT INTO trainer VALUES ('Fisherman Elliot','13, 31');
INSERT INTO trainer VALUES ('Rocker Luca','13, 14, 34');
INSERT INTO trainer VALUES ('Camper Justin','13, 30');
INSERT INTO trainer VALUES ('Fisherman Andrew','13, 14, 33');
INSERT INTO trainer VALUES ('Picnicker Alma','30');
INSERT INTO trainer VALUES ('Bird Keeper Sebastian','50, 47');
INSERT INTO trainer VALUES ('Picnicker Susie','74, 115');
INSERT INTO trainer VALUES ('Beauty Lola','13, 31');
INSERT INTO trainer VALUES ('Beauty Sheila','13, 14, 34');
INSERT INTO trainer VALUES ('Picnicker Valerie','31');
INSERT INTO trainer VALUES ('Picnicker Gwen','50, 48');
INSERT INTO trainer VALUES ('Bird Keeper Perry','74, 116');
INSERT INTO trainer VALUES ('Biker Jared','13, 32');
INSERT INTO trainer VALUES ('Bird Keeper Robert','13, 14, 35');
INSERT INTO trainer VALUES ('Bird Keeper Carter','13, 31');
INSERT INTO trainer VALUES ('Bird Keeper Mitch','13, 14, 34');
INSERT INTO trainer VALUES ('Bird Keeper Marlon','31');
INSERT INTO trainer VALUES ('Bird Keeper Beck','50, 48');
INSERT INTO trainer VALUES ('Bird Keeper Donald','74, 116');
INSERT INTO trainer VALUES ('Bird Keeper Benny','13, 32');
INSERT INTO trainer VALUES ('Biker Geralk','13, 14, 35');
INSERT INTO trainer VALUES ('Biker Malik','32');
INSERT INTO trainer VALUES ('Biker Isaac','50, 49');
INSERT INTO trainer VALUES ('Biker Lukas','74, 117');
INSERT INTO trainer VALUES ('Picnicker Becky','13, 33');
INSERT INTO trainer VALUES ('Picnicker Celia','13, 14, 36');
INSERT INTO trainer VALUES ('Biker Ernest','13, 32');
INSERT INTO trainer VALUES ('Biker Alex','13, 14, 35');
INSERT INTO trainer VALUES ('Beauty Grace','32');
INSERT INTO trainer VALUES ('Beauty Olivia','50, 49');
INSERT INTO trainer VALUES ('Picnicker Kindra','74, 117');
INSERT INTO trainer VALUES ('Bird Keeper Chester','13, 33');
INSERT INTO trainer VALUES ('Bird Keeper Edwin','13, 14, 36');
INSERT INTO trainer VALUES ('Picnicker Yazmin','33');
INSERT INTO trainer VALUES ('Swimmer (M) Richard','50, 50');
INSERT INTO trainer VALUES ('Swimer (M) Reece','74, 118');
INSERT INTO trainer VALUES ('Swimmer (M) Tony','13, 34');
INSERT INTO trainer VALUES ('Swimmer (M) David','13, 14, 37');
INSERT INTO trainer VALUES ('Swimmer (M) Douglas','13, 33');
INSERT INTO trainer VALUES ('Swimmer (M) Matthew','13, 14, 36');
INSERT INTO trainer VALUES ('Swimmer (M) Axle','33');
INSERT INTO trainer VALUES ('Swimmer (F) Alice','50, 50');
INSERT INTO trainer VALUES ('Swimmer (F) Connie','74, 118');
INSERT INTO trainer VALUES ('Swimmer (F) Anya','13, 34');
INSERT INTO trainer VALUES ('Swimmer (M) Barry','74, 116');
INSERT INTO trainer VALUES ('Swimmer (M) Darrin','13, 32');
INSERT INTO trainer VALUES ('Swimmer (F) Shirley','13, 14, 35');
INSERT INTO trainer VALUES ('Swimmer (F) Tiffany','32');
INSERT INTO trainer VALUES ('Picnicker Irene','50, 49');
INSERT INTO trainer VALUES ('Bird Keeper Roger','74, 117');
INSERT INTO trainer VALUES ('Swimmer (F) Nora','13, 33');
INSERT INTO trainer VALUES ('Swimmer (M) Dean','13, 14, 36');
INSERT INTO trainer VALUES ('Picnicker Missy','13, 32');
INSERT INTO trainer VALUES ('Swimmer (F) Melissa','13, 14, 35');
INSERT INTO trainer VALUES ('Youngster Johnson','32');
INSERT INTO trainer VALUES ('Scientist Ted','50, 49');
INSERT INTO trainer VALUES ('Burglar Arnie','74, 117');
INSERT INTO trainer VALUES ('Burglar Simon','13, 33');
INSERT INTO trainer VALUES ('Scientist Braydon','13, 14, 36');
INSERT INTO trainer VALUES ('Burglar Lewis','33');
INSERT INTO trainer VALUES ('Scientist Ivan','50, 50');
INSERT INTO trainer VALUES ('Burglar Quinn','74, 118');
INSERT INTO trainer VALUES ('Super Nerd Erik','13, 34');
INSERT INTO trainer VALUES ('Super Nerd Avery','13, 14, 37');
INSERT INTO trainer VALUES ('Burglar Ramon','13, 33');
INSERT INTO trainer VALUES ('Super Nerd Derek','13, 14, 36');
INSERT INTO trainer VALUES ('Burglar Dusty','33');
INSERT INTO trainer VALUES ('Super Nerd Zac','50, 50');
INSERT INTO trainer VALUES ('Leader Blaine','74, 118');
INSERT INTO trainer VALUES ('Fisherman Wade','13, 34');
INSERT INTO trainer VALUES ('Fisherman Ronald','13, 14, 37');
INSERT INTO trainer VALUES ('Swimmer (M) Spencer','34');
INSERT INTO trainer VALUES ('Fisherman Claude','50, 51');
INSERT INTO trainer VALUES ('Fisherman Nolan','74, 119');
INSERT INTO trainer VALUES ('Swimmer (M) Jack','13, 35');
INSERT INTO trainer VALUES ('Swimmer (M) Roland','13, 14, 38');
INSERT INTO trainer VALUES ('Swimmer (M) Jerome','13, 34');
INSERT INTO trainer VALUES ('Tamer Cole','13, 14, 37');
INSERT INTO trainer VALUES ('Black Belt Kiyo','34');
INSERT INTO trainer VALUES ('Cool Trainer Samuel','50, 51');
INSERT INTO trainer VALUES ('Cool Trainer Yuji','74, 119');
INSERT INTO trainer VALUES ('Black Belt Atsushi','13, 35');
INSERT INTO trainer VALUES ('Tamer Jason','74, 117');
INSERT INTO trainer VALUES ('Cool Trainer Warren','13, 33');
INSERT INTO trainer VALUES ('Black Belt Takashi','13, 14, 36');
INSERT INTO trainer VALUES ('Leader Giovanni','33');
INSERT INTO trainer VALUES ('Rival','50, 50');
INSERT INTO trainer VALUES ('Cool Trainer Naomi','74, 118');
INSERT INTO trainer VALUES ('Cool Trainer Rolando','13, 34');
INSERT INTO trainer VALUES ('Black Belt Daisuke','13, 14, 37');
INSERT INTO trainer VALUES ('Juggler Nelson','13, 33');
INSERT INTO trainer VALUES ('Tamer Vincent','13, 14, 36');
INSERT INTO trainer VALUES ('Juggler Gregory','33');
INSERT INTO trainer VALUES ('Cool Trainer George','50, 50');
INSERT INTO trainer VALUES ('Pokemanic Dawson','74, 118');
INSERT INTO trainer VALUES ('Cool Trainer Alexa','13, 34');
INSERT INTO trainer VALUES ('Cool Trainer Colby','13, 14, 37');
INSERT INTO trainer VALUES ('Cool Trainer Caroline','34');
INSERT INTO trainer VALUES ('Cool Couple Ray & Tyra','50, 51');
INSERT INTO trainer VALUES ('Elite Four Lorelei','74, 119');
INSERT INTO trainer VALUES ('Elite Four Bruno','13, 35');
INSERT INTO trainer VALUES ('Elite Four Agatha','13, 14, 38');
INSERT INTO trainer VALUES ('Elite Four Lance','13, 34');
INSERT INTO trainer VALUES ('Champion Rival','13, 14, 37');
